### ISSUE TITLE
Variables used inside filter don't work

### ISSUE THREAD

**Issue by Vinss85** [neo4j-graphql/neo4j-graphql#109]
Hi,
I'm testing this plugin against Neo4j 3.4 to evaluate the possibility of an architectural change,
I find it very interesting.
I've some questions though:
1 - Is it somehow possible to embedd the /graphql route in an express application? Say to add some logging and security middlewares? Or would you suggest to use cypher procedure call to execute a query though the javascript driver?
2 - When I tried a simple scenario I had a problem with using variables inside a query filter. With postman I try to POST the following body:

{
  "query": "query($text: String) { Site(orderBy: Name_asc, filter: {Name_contains: $text}) { Name } }",
  "variables": { "text": "Enem"}
}

but I get an empty result, indeed if I use the text directly in the filter value it works. What am I missing?

Thanks :)

**Comment by jexp** [comment]
Were you able to test this?
