### ISSUE TITLE
Partial update

### ISSUE THREAD

**Issue by fatjoni** [neo4j-graphql/neo4j-graphql#111]
Hi,

I tried to do a partial update and all the other attributes were nulled.
Maybe i am not handling it correctly but couldnt find any information in the documentation.
Thanks in advance :)

**Comment by jexp** [comment]
Can you share the full mutation code you ran and the schema?

**Comment by fatjoni** [comment]
Hi and thank you for your reply.
Here is the portion of the schema: 
 type Job  {
    amount: Int
    bet: Int
    id: String!
    match: String
    minOdd: Float
    machine: [Machine] @relation(name:"MACHINE_TO_USE",direction:OUT)
    status: Boolean
    currentOdd: Float
    msg: String
  }

and here is the mutation i am calling:
mutation{
  updateJob(id:"ffsfs",status:false)
}

If i do call this on an existing record, all the other fields are nulled and only the id and status are available(the updated ones)

**Comment by jexp** [comment]
should be fixed in the next release today, please check after it is out.

**Comment by jexp** [comment]
Were you able to test this?

**Comment by jorroll** [comment]
Having just tested, this issue, as described, has been fixed.
