### ISSUE TITLE
Code generation with graphql-binding 

### ISSUE THREAD

**Issue by playerx** [neo4j-graphql/neo4j-graphql#113]
Hi,

I'm trying to do code generation using graphql-binding, one issue that Im having is that graphql-js expects root types as Query, Mutation, Subscription. Or there should be Kind.SCHEMA_DEFINITION node which will describe operationTypes:
https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L176

**Comment by jexp** [comment]
How does it fail exactly? How can I reproduce it?

At least for GraphIQL it seems to work with introspection queries.

**Comment by playerx** [comment]
I've created [remote-graphql-binding](https://github.com/jokio/remote-graphql-binding), which is fork of prisma-binding, with little changes and after that I've tried to create sample project with .graphqlconfig and imported neo4j-graphql endpoint using remote-graphql-binding

.graphqlconfig
```js
{
  "projects": {
    "Test": {
      "schemaPath": "schemas/db.graphql",
      "extensions": {
        "endpoints": {
          "dev": {
            "url": "http://localhost:7474/graphql/",
            "headers": {
              "Authorization": "basic bmVvNGo6MTIz"
            }
          }
        },
        "codegen": [
          {
            "generator": "remote-graphql-binding",
            "language": "typescript",
            "output": {
              "binding": "src/generated/prisma.ts"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by playerx** [comment]
Also I've tested remote-graphql-binding with another graphql endpoints (created by graphql-yoga, with operationTypes: Query, Mutation, Subscription) and it worked correctly.

After debugging I've found that schema.getQueryType() returns null (graphql-js) for neo4j-graphql endpoint

**Comment by playerx** [comment]
simplest way to reproduce:

1. create new project with .graphqlconfig file (that I've shared)
2. run `graphql get-schema -p Test`
3. run `graphql codegen`

**Comment by playerx** [comment]
Also I've tried something like this, but It still generated QueryType & MutationType
```gql
CALL graphql.idl('

type Movie  {
  title: String!
  released: Int
  actors: [Person] @relation(name:"ACTED_IN",direction:IN)
  directors: [Person] @cypher(statement:"MATCH (this)<-[:DIRECTED]-(d) RETURN d")
}
type Person {
  name: String!
  born: Int
  movies: [Movie] @relation(name:"ACTED_IN")
}
schema {
   query: Query
   mutation: Mutation
}
type Query {
  coActors(name:ID!): [Person] @cypher(statement:"MATCH (p:Person {name:$name})-[:ACTED_IN]->()<-[:ACTED_IN]-(co) RETURN distinct co")
}
type Mutation {
  rateMovie(user:ID!, movie:ID!, rating:Int!): Int
  @cypher(statement:"MATCH (p:Person {name:$user}),(m:Movie {title:$movie}) MERGE (p)-[r:RATED]->(m) SET r.rating=$rating RETURN r.rating")
}

')
```

**Comment by playerx** [comment]
One more update, I've created simple apollo-server, which just wrapped current neo4j-graphql service and codegen worked successfully

Sharing apollo-server source code:
```ts
import { GraphQLSchema } from 'graphql'
import { HttpLink } from 'apollo-link-http'
import { ApolloServer, mergeSchemas, introspectSchema, makeRemoteExecutableSchema } from 'apollo-server'

export async function getRemoteSchema(uri): Promise<GraphQLSchema> {
	const link = new HttpLink({ uri, fetch, headers: { Authorization: 'basic bmVvNGo6MTIz' } })
	const introspectionSchema = await introspectSchema(link)
	return makeRemoteExecutableSchema({
		schema: introspectionSchema,
		link,
	})
}

async function run() {
	const remoteSchema = await getRemoteSchema('http://localhost:7474/graphql/')

	const schema = mergeSchemas({
		schemas: [remoteSchema],
	})

	const server = new ApolloServer({
		schema,
	})

	server.listen().then(({ url }) => {
		console.log(`🚀  Server ready at ${url}`)
	})
}

run()
```
It changed operationTypes to Query, Mutation, Subscription

**Comment by playerx** [comment]
Updates:
I've checked more details and it seems that there is an issue in Typescript generator, when I tried to generate javascript code directly from neo4j-graphql service it worked

**Comment by playerx** [comment]
So, there was an issue in graphql-import library, there was hardcoded Query, Mutation, Subscription, I've already sent pull request for that:
https://github.com/prismagraphql/graphql-import/pull/197

I've created remote-graphql-binding, which can be used to generate sdk (on Typescript) for neo4j database and not only (for any graphql service)
https://github.com/jokio/remote-graphql-binding

It already works :) there is example in remote-graphql-binding readme
