### ISSUE TITLE
How to return ID of neo4j node using graphql ? 

### ISSUE THREAD

**Issue by ziiko10** [neo4j-graphql/neo4j-graphql#120]

**Comment by fatjoni** [comment]
You can get the id of the node via this parameter:   _id

**Comment by ziiko10** [comment]
Hello @fatjoni thank your for your response.
But actually, when i use the _id attribute , it return "cannot return null for non-nullable field" , even when i use @cypher statement , it return :  "_id" : null .

**Comment by jexp** [comment]
@AbbesBendaoud10 can you share your schema and the query you run to return the _id ?

**Comment by ziiko10** [comment]
Hello @jexp  thank your for your response, .


![github2](https://user-images.githubusercontent.com/18125884/42370712-bf59d3fe-810d-11e8-9fa4-23706a9dba75.png)
![github](https://user-images.githubusercontent.com/18125884/42370737-d13c42dc-810d-11e8-8559-c0a0a262b316.png)

**Comment by fatjoni** [comment]
Please do not define in your schema the id. It is automatically generated by default. Update the schema and i believe everything will be okay

**Comment by ziiko10** [comment]
@fatjoni  Not works !

**Comment by fatjoni** [comment]
Can you send me once more a screenshot of the schema the query and the response?

**Comment by ziiko10** [comment]
![error](https://user-images.githubusercontent.com/18125884/42377318-22698524-8123-11e8-9211-a4bd3400b3eb.png)
 This is the error when i remove the _id attribute from my schema .

**Comment by fatjoni** [comment]
Can you please test a simple query like 
{
groups{
_id
name
}
}

and send me the feedback?

**Comment by ziiko10** [comment]
I expected you to say that , but this query works due to neo4jgraphql plugin , but when i used into another query its doesn't works.

**Comment by jexp** [comment]
The dark themed schema is really hard to read. Can you share exactly what you did in terms of schema changes as plain text, not screenshots?

And where your schema types are not getting auto-generated queries that automatically return `_id` fields?

**Comment by ziiko10** [comment]
Sorry for the theme , this is the query which make me the error . 
The type of group_to_verify is : Group .
**userGetGroupsByRange(user_id:955,email:"farhatabbes.bendaoud@esprit.tn"){
groups_to_verify{
  _id
  name
  }
}**

This is the signature of my function : 
**userGetGroupsByRange(user_id: Int!, email: String!) : [UserGroupRelation]**

And this is my UserGroupRelation type : 
**type UserGroupRelation {
	groups_belongs : [Group]
	groups_to_verify: [Group]
	groups: [Group]
}**

**Comment by jexp** [comment]
If you are using neo4j-graphql extension,  you're missing the `@relation` directives.

and the query `userGetGroupsByRange` is also not auto-generated, so you need to have a resolver that produces that (or an `@cypher` directive on the query)

**Comment by ziiko10** [comment]
@jexp  Of course i have  a resolver and my function worked well but the only think is that it not return the id of nodes . 
This my query : 
**exports._getByRanges =
	`MATCH (user:User)
WHERE ID(user) = $user_id
OPTIONAL MATCH (user)-[r:BELONGS {email:$email}]->(belongs:Group)
OPTIONAL MATCH (user)-[r2:TO_VERIFY {email: $email} ]->(verify:Group)
OPTIONAL MATCH (groups:Group {email_range: $email_range} )
WHERE NOT (user)-[:BELONGS|TO_VERIFY]->(groups) 
WITH PROPERTIES(belongs) as b, PROPERTIES(verify) as v, PROPERTIES(groups) as g
RETURN {
	groups_belongs : [b],
	groups_to_verify : [v],
	groups : [g] 
} AS b**

and this is how i run my function in my node js code : 
	**var data = await Neo4j.session.run(_getByRanges, { user_id, email, email_range });
	return data.records.map(record => {
		return record.get('b');
	});**

Everthing worked well , but i dont have the field **id** of neo4j nodes in my graphql endpoint.

**Comment by ziiko10** [comment]
Fixing it by adding this : 
**groups_belongs : [ b { .*, _id: toInt(id(belongs))} ]**
