### ISSUE TITLE
Hello , can I add node as parameter of "apoc.do.case" function like this ??

### ISSUE THREAD

**Issue by ziiko10** [neo4j-graphql/neo4j-graphql#121]
![cypher](https://user-images.githubusercontent.com/18125884/42372473-8f84b234-8112-11e8-849b-d6168ac3fa18.png)
![cypher2](https://user-images.githubusercontent.com/18125884/42372480-92e8417a-8112-11e8-84f7-cc9e94636c50.png)

**Comment by jexp** [comment]
*Please don't use dark on dark screenshots.*

If your entities are `null` you cannot use them in a match, you'll need to include the non-null check into your condition.

**Comment by ziiko10** [comment]
No my entities are not "null" when i return them , i have a result , but when i use them to create relationship between them , i get an error
