### ISSUE TITLE
Hello , I have an  error with apoc.do.case . If someone know what is wrong 

### ISSUE THREAD

**Issue by ziiko10** [neo4j-graphql/neo4j-graphql#122]
![error](https://user-images.githubusercontent.com/18125884/42380404-19087c50-812e-11e8-9dda-a025c8aa1426.png)

**Comment by jexp** [comment]
Oh, why do you do the `collect` aggregation? 
That's not necessary at all. Just use `event1` and `user1`

**Comment by ziiko10** [comment]
Thank you @jexp  , it works  !!!
