### ISSUE TITLE
Wrong behavior+Return relation props question.

### ISSUE THREAD

**Issue by rashad-mohamed-gehan** [neo4j-graphql/neo4j-graphql#157]
![001](https://user-images.githubusercontent.com/13349804/50150475-c1388e00-02c6-11e9-87eb-80b9851d3efc.PNG)
![002](https://user-images.githubusercontent.com/13349804/50150477-c1388e00-02c6-11e9-9ba6-6b31c14df652.PNG)

Wrong behavior: database already has [twitter] property in some [SocialProfile] nodes.
Return relation props question : database has [word_count_new] property in [hasPersonalityTraits] relation, how i can return it.

thanks.

**Comment by jexp** [comment]
The current implementation for the generaion only samples on a few nodes.

I think you'd fare better with a schema file that you send to the database where you have full control.

Support for properties on relationships will come after we integrate neo4j-graphql-java as the graphql->cypher translator, there that already works.

**Comment by rashad-mohamed-gehan** [comment]
neo4j-graphql-java!
 what about .Net developers?

**Comment by jexp** [comment]
If it's integrated in the backend the GraphQL API is the same.

I just mean that the feature development happens currently in that libary.
