### ISSUE TITLE
getIdl() equivalent in neo4j-graphql 3.5

### ISSUE THREAD

**Issue by mayurbhangale** [neo4j-graphql/neo4j-graphql#160]
When trying to execute `RETURN graphql.getIdl()` as mentioned in README in neo4j-graphql v3.5, plugin throws error `Neo.ClientError.Statement.SyntaxError: Unknown function 'graphql.getIdl' (line 1, column 8 (offset: 7)) "RETURN graphql.getIdl()" ^`

**Comment by mayurbhangale** [comment]
Update:
There seems to be getIdl() in 3.5.0.1, though after installing from release JAR, It says Unknown Function
https://github.com/neo4j-graphql/neo4j-graphql/blob/d86ca341c06bed4f6619f2c27bce400aa6d3d415/src/main/kotlin/org/neo4j/graphql/GraphQLProcedure.kt#L71

**Comment by jexp** [comment]
How did you install the new version? And are there any whitelist configs in your neo4j.conf / settings?

**Comment by mayurbhangale** [comment]
@jexp copied JAR to plugins directory. Added:
`dbms.security.procedures.unrestricted=apoc.*,graphql.*
dbms.security.procedures.whitelist=graphql.*,`
to `neo4j.conf`.

I have access to all other functions such as `idl()`,` query()` but not `getIdl()`

**Comment by jexp** [comment]
Odd then, I guess it hand't made it into the release yet.

**Comment by mvid** [comment]
Having the same issue. Running Neo4j 3.5.2 in Docker, with the 3.5.0.1 plugin, copied in via jar. `graphql.schema()` works fine, but `graphql.getIdl()` returns UNKNOWN FUNCTION. Running with the configs listed for docker in the readme. Everything else seems to be working.

**Comment by oldalgazda** [comment]
Hi, same issue here. What can we expect - or is there a workaround to get somehow that automatically generated schema? I just would like to build upon that, not really creating a schema from scratch. Thank you!

**Comment by mvid** [comment]
@jexp the `getIdl()` function would be useful for defining a proxy

**Comment by jexp** [comment]
I did a new release see here: https://github.com/neo4j-graphql/neo4j-graphql/releases/tag/3.5.0.2

**Comment by oldalgazda** [comment]
thank you very much, it works!
