### ISSUE TITLE
@cypher passThrough: true in type field

### ISSUE THREAD

**Issue by nmonterroso** [neo4j-graphql/neo4j-graphql#162]
I'm having an issue when running the following on Neo4j v3.5.0 using the neo4j-graphql-server plugin v3.5.0.1. 

Given the schema:
```
type TypeA {
    uuid: ID!
    foo: String!
    bLinks: [BLink!]! @cypher(statement:"WITH {this} as this MATCH(this)-[bLink:b_link]-(b:TypeB) RETURN {relProp: bLink.relProp, typeB: b }", passThrough:true)
}

type BLink {
    relProp: String!
    typeB: TypeB!
}

type TypeB {
    uuid: ID!
    foo: String!
}
```

With data:
```
create(:TypeA {uuid: "1", foo:"typeA-1"})-[:b_link {relProp: "foo"}]->(:TypeB {uuid: "2", foo:"typeB-1"})
```

I want to query:
```
query {
  TypeA {
    bLinks {
      relProp
      typeB {
        foo
      }
    }
  }
}
```
When I do this I get the error: `Expected to find a node at ref slot 0 but found Map{typeB -> (2), relProp -> String("foo")} instead`

With query logging enabled I see that the Cypher being run for this GraphQL query is: 
```
MATCH (`typeA`:`TypeA`)
RETURN graphql.labels(`typeA`) AS `_labels`,
[ x IN graphql.runMany('WITH {this} as this MATCH(this)-[bLink:b_link]-(b:TypeB) RETURN {relProp: bLink.relProp, typeB: b }', {`this`:`typeA`}) | `x` {`_labels` : graphql.labels(`x`), .`relProp`, `typeB` : head([ (`x`)-[:`typeB`]->(`x_typeB`:`TypeB`)  | `x_typeB` {`_labels` : graphql.labels(`x_typeB`), .`foo`}])} ] AS `bLinks`
```
From the note [here](https://github.com/neo4j-graphql/neo4j-graphql/tree/3.5#features) and #76 it seems like `passThrough: true` should work, even though `BLink` is not an actual `node` but a plain map object. The error/generated Cypher is the same regardless of the `passThrough` setting. I see where the check is being done in [`executeCypher`](https://github.com/neo4j-graphql/neo4j-graphql/blob/3.5/src/main/kotlin/org/neo4j/graphql/GraphQLSchemaBuilder.kt#L118) for the `passThrough` setting, so I'm probably misunderstanding something.

I also ran through the steps from [this](https://github.com/neo4j-graphql/neo4j-graphql/blob/e8400c3c2d775b84d9e19ae358c32f4ca42ff4ef/src/test/java/org/neo4j/graphql/EndToEndTest.kt#L241) test and _that_ seems to work properly, though it's not exactly the same since the `@cypher` directive is part of a function without additional fields.

Any help is appreciated.

**Comment by jexp** [comment]
Hi, thanks a lot for your detailed issue.

As far as I can remember and see in the code, passThrough was only implemented so far for dynamic top-level queries and mutations.

in your case the returned value `{relProp: bLink.relProp, typeB: b }` is still treated as a node, i.e. it tries to expand further down.

So this is a lack of clarity about the limit in the docs and not having it implemented. Sorry for that.

It works when you leave off that drill-down:

```
call graphql.query('
query {
  TypeA {
    bLinks {
      relProp
    }
  }
}
')
```

what you could do to work around, is to add the properties of the node typeB to the result map:

```
@cypher(statement:"WITH {this} as this MATCH(this)-[bLink:b_link]-(b:TypeB) RETURN b { .*, relProp: bLink.relProp }
```

and then add them as top-level to the BLink type.

```
type BLink {
    relProp: String!
    uuid: ID!
    foo: String!
}
```

then your query like this should work:

```
call graphql.query('
query {
  TypeA {
    bLinks {
      relProp
      uuid
      foo
    }
  }
}
')
```

returning

```
{
  "TypeA": [
    {
      "bLinks": [
        {
          "uuid": "2",
          "relProp": "foo",
          "foo": "typeB-1"
        }
      ]
    }
  ]
}
```

full schema:

```
call graphql.idl('
type TypeA {
    uuid: ID!
    foo: String!
    bLinks: [BLink!]! @cypher(statement:"WITH {this} as this MATCH(this)-[bLink:b_link]-(b:TypeB) RETURN b { .*, relProp: bLink.relProp }")
}

type BLink {
    relProp: String!
    uuid: ID!
    foo: String!
}

')
```

**Comment by jexp** [comment]
If you have time and interest, I'd love a PR, not sure when I otherwise would get to this, as I plan to replace the translator with https://github.com/neo4j-graphql-java

**Comment by jexp** [comment]
As you seem pretty experienced in this, I'd love contributions in general. 

If you want to chat about your usage of graphql+neo4j, drop me an email to michael at neo4j.com

**Comment by nmonterroso** [comment]
@jexp thanks for the quick reply! 

I was wondering if `passThrough` only applied to the top-level queries of the schema, thanks for verifying that. Also, your suggested workaround is my current approach, was just hoping for something a bit more structured. 

I've looked at [`neo4j-graphql-java`](https://github.com/neo4j-graphql/neo4j-graphql-java), and it seems to support what I'm looking for with [`@relation on Types`](https://github.com/neo4j-graphql/neo4j-graphql-java#relationship-on-types). I think if the plan is to replace the translator in this plugin then any contributions might be better served in that project. What do you think? 

Since `passThrough` is only intended on top-level queries and mutations I'll close out this issue.

**Comment by jexp** [comment]
Yes you're right, contributions there are better.
I'm currently looking into adding auto-generated queries and mutations.
There is a todo-list in the readme and GH issues so if you're interested, ping me and we can look at something that you could help with.
