### ISSUE TITLE
unable to pass order parameter to nested @cypher directive

### ISSUE THREAD

**Issue by terryf82** [neo4j-graphql/neo4j-graphql#163]
With the following Destination and PointOfInterest types:

```
type Destination {
  vendorId: String!
  name: String!
  poisByTag(maxDistance: Int!, tag: String!): [PointOfInterest] @cypher(statement:"MATCH (this)-[r:SHARES_COUNTRY]-(p:PointOfInterest) WHERE r.distance <= $maxDistance AND p.primaryTag = $tag RETURN p { .*, distance:r.distance} ORDER BY p.distance ASC")
}

type PointOfInterest {
  vendorId: String!
  name: String!
  primaryTag: String
  distance: Float
}
```

I am able to retrieve data using this query:
```
query getDestinationWithPoisByTag($candidateId: String!) {
  Destination(vendorId: $candidateId) {
    name
    poisByTag(tag:"Beach", maxDistance: 30000) {
      name
      distance
    }
  }
}
```

However there seems to be no way to override the hard-coded `ORDER BY` statement by parameter. With this updated Destination type:

```
type Destination {
  vendorId: String!
  name: String!
  poisByTag(maxDistance: Int!, tag: String!, order: String!): [PointOfInterest] @cypher(statement:"MATCH (this)-[r:SHARES_COUNTRY]-(p:PointOfInterest) WHERE r.distance <= $maxDistance AND p.primaryTag = $tag RETURN p { .*, distance:r.distance} ORDER BY $order")
}
```

and this updated query:

```
query getDestinationWithPoisByTag($candidateId: String!) {
  Destination(vendorId: $candidateId) {
    name
    poisByTag(tag:"Beach", maxDistance: 300000, order: "distance asc") {
      name
      distance
    }
  }
}
```

The results are not ordered by distance. The query log from Neo4J looks ok

```
`destination`.`name` AS `name`,
[ x IN graphql.runMany('WITH {this} AS this MATCH (this)-[r:SHARES_COUNTRY]-(p:PointOfInterest) WHERE r.distance <= $maxDistance AND p.primaryTag = $tag RETURN p { .*, distance:r.distance} ORDER BY $order', {`this`:`destination`,`tag`:"Beach",`maxDistance`:300000,`order`:"distance asc"}) | `x` {`_labels` : graphql.labels(`x`), .`name`, .`distance`} ] AS `poisByTag`
```
but $order is not being picked up. I can even enter an invalid value e.g `order: "distance asccccccc"` and the result set doesn't change, and no error is generated.

**Comment by jexp** [comment]
Oh I think I know what's happening.

`ORDER BY takes an expression`, e.g. `ORDER BY n.foo[0].prio`
and your parameter is used as taht expression, so it does

`ORDER BY "distance asc"`

which of course doesn't affect the output.

And parameters cannot access the variables of the query.
So the correct way to support this is to use/support ordering support for fields.

**Comment by jexp** [comment]
But supporting that correctly in a generic way wouldn't work b/c we cannot know what type to order by, e.g. using something like `_LocationOrdering` enum wouldn't work. b/c one migh refer to the relationship or something else.

But while experimenting with this I had another idea which actually works well.
Because `ORDER BY` supports expressions it also supports `CASE` expressions.
So we can use that to map from the input string to the actual expression like this:

```
type Destination {
  vendorId: String!
  name: String!
  poisByTag(maxDistance: Int!, tag: String!): [PointOfInterest] 
  @cypher(statement:
"MATCH (this)-[r:SHARES_COUNTRY]-(p:PointOfInterest) 
WHERE r.distance <= $maxDistance AND p.primaryTag = $tag 
RETURN p { .*, distance:r.distance} 
ORDER BY CASE $order 
  WHEN \'distance\' THEN r.distance 
  WHEN \'name\' THEN p.name END 
  // this is optional generic
  ELSE p[$order]
ASC")
}
```

It might even work to use

`RETURN p { .*, distance:r.distance}  as result ORDER BY result[$order] ASC`
This at least works for an enumerated set of input values (and optionally we could even use properties.

Please try it out and let me know if this works for you.

**Comment by terryf82** [comment]
@jexp your second suggestion works quite well:
`RETURN p { .*, distance:r.distance} as result ORDER BY result[$order] ASC`

with the only limitation being that ASC is hard-coded into the query. Ideally I would like to be able to provide that by input string.

I tried adapting the first suggestion to achieve this:
```
type Destination {
  vendorId: String!
  name: String!
  poisByTag(maxDistance: Int!, tag: String!, order: String!): [PointOfInterest] @cypher(statement:"MATCH (this)-[r:SHARES_COUNTRY]-(p:PointOfInterest) WHERE r.distance <= $maxDistance AND p.primaryTag = $tag RETURN p { .*, distance:r.distance} ORDER BY CASE $order WHEN \'distance_asc\' THEN r.distance ASC WHEN \'distance_desc\' THEN r.distance DESC ELSE p.name ASC END")
}
```

but I must not have the syntax right, because running this query:
```
query getDestinationWithPoisByTag($candidateId: String!) {
  Destination(vendorId: $candidateId) {
    name
    poisByTag(tag:"Monument", maxDistance: 500000, order: "distance_desc") {
      name
      distance
    }
  }
}
```

generates this error:
```
"statusCode": "Neo.ClientError.Statement.SyntaxError",
        "message": "Invalid input 'd': expected whitespace, '.', node labels, '[', \"=~\", IN, STARTS, ENDS, CONTAINS, IS, '^', '*', '/', '%', '+', '-', '=', '~', \"<>\", \"!=\", '<', '>', \"<=\", \">=\", AND, XOR, OR, ',' or ')' (line 5, column 217 (offset: 375))\n\"[ x IN graphql.runMany('WITH {this} AS this MATCH (this)-[r:SHARES_COUNTRY]-(p:PointOfInterest) WHERE r.distance <= $maxDistance AND p.primaryTag = $tag RETURN p { .*, distance:r.distance} ORDER BY CASE $order WHEN 'distance_asc' THEN r.distance ASC WHEN 'distance_desc' THEN r.distance DESC ELSE p.name ASC END', {`this`:`destination`,`tag`:\"Monument\",`maxDistance`:500000,`order`:\"distance_desc\"}) | `x` {`_labels` : graphql.labels(`x`), .`name`, .`distance`} ] AS `poisByTag`\"\n
```

Thanks for your help.

**Comment by jexp** [comment]
yes that's a drawback
you could try 

```
ORDER BY 
case when $order starts with '^' then result[substring($order,1)] else null end ASC,
case when $order starts with '^' then null else result[$order] end DESC,
```

and use `^name` for ascending and `name` for descending order as the always other one will turn into null.

**Comment by terryf82** [comment]
Your comment about ORDER BY:

> `ORDER BY takes an expression`, e.g. `ORDER BY n.foo[0].prio`

has got me thinking about my _tag_ parameter. Ideally I would like to load _poisByTag_ with:
```
poisByTag(first: 3, tag: $tag, maxDistance: 50000, order: "distance") {
```

and then adjust $tag via the Query Variables. But if I try this, the logged query parameters change from:
```
...{`this`:`destination`,`first`:3,`tag`:"Beach",...
```

to
```
...{`this`:`destination`,`first`:3,`tag`:"{`tag`}",...
```

Would a similar workaround be required to support this type of use? I have over 200 different tags to support so would like to avoid a case statement handling all of them if possible.

Thanks.

**Comment by jexp** [comment]
Oh that seems to be a bug in rendering cypher directive parameter that we need to fix.

**Comment by terryf82** [comment]
@jexp is this the issue (in CypherGenerator.kt)?
```
fun formatValue(value: Value?): String =
   when (value) {
   is VariableReference -> "{`${value.name}`}"
   // todo turn into parameters  !!
...
```

**Comment by jexp** [comment]
Not only, it's later somewhere where those are then rendered for the inline execution.

**Comment by jexp** [comment]
this one https://github.com/neo4j-graphql/neo4j-graphql/blob/3.4/src/main/kotlin/org/neo4j/graphql/CypherGenerator.kt#L239

**Comment by jexp** [comment]
Fixed it, if you want to, you can try to build it locally or use this.

https://www.dropbox.com/s/itnb0aqjpszx1ra/neo4j-graphql-3.4.0.1.jar?dl=0

**Comment by terryf82** [comment]
@jexp works perfectly, thanks!
