### ISSUE TITLE
NeoServletContainer,-1,false

### ISSUE THREAD

**Issue by smccamley** [neo4j-graphql/neo4j-graphql#20]
Hi there,

I followed the instructions in your readme to the letter, but on restarting my neo4j server I found this error 

`Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-673720ea@f0284693==org.neo4j.server.web.NeoServletContainer,-1,false`

I'm not sure where the error is

neo4j version 3.1.3
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.1", arch: "x86_64", family: "mac"

**Comment by jexp** [comment]
In which log did you see that? 
Anything in debug.log ?

Did your server start?

**Comment by smccamley** [comment]
I saw this message in a popup when attempting to start the server from a gui.
The server did not start. There seems to be no additional details in a log in the locations I would expect to see a log. Just investigating now...

**Comment by smccamley** [comment]
After an hour of digging and some desperation I restarted my computer. Now it's working. Nothing changed. No idea what the problem was. Thank you @jexp for taking a look too!
