### ISSUE TITLE
Issues with graphql schema formatting

### ISSUE THREAD

**Issue by topher** [neo4j-graphql/neo4j-graphql#21]
I have been storing data with Neo4j, and now would like to model a graphql schema compatible with both relay and neo4j-graphql. 

I'm currently testing my schema based off a sample data returned from a neo4j query, but am not getting a valid response with sample data. After reading the docs, I am using the schema below. 

![](https://i.stack.imgur.com/iE2wl.png)

Above you can see the PERFORMED_FOR_Affiliation is null, though it is defined in the schema as an Affiliation type.

```
type Query {
      affiliations(affn_id: ID): [Affiliation]
      performances(pfrm_id: ID): [Performance]
      PERFORMED_FOR_Affiliation(affn_id: ID): Affiliation
      Performance_PERFORMED_FOR(pfrm_id: ID): Performance
    }
```

PERFORMED_FOR_Affiliation query is similar to an affiliations query only the relationship should return only 1 affiliation (with a matching uid).

![](https://i.stack.imgur.com/jUPo5.png)

I assume affn_id is not being passed down correctly and not sure how to do that properly. Does the PERFORMED_FOR_Affiliation need its own schema. I've seen relay uses graqhql schemas for 'nodes' and 'edge' types. 

Schema
```
type Performance {
    pfrm_id: ID!
    mark: Int
    affn_id: String
    PERFORMED_FOR_Affiliation: Affiliation
}

type Affiliation {
    Performance_PERFORMED_FOR: Performance 
    affn_id: ID!
    name: String
}
```

I'm only testing the queries on static data w/o neo4j-graphql. Is there something I'm missing? 

Also, What are fundamental differences with neo4j schema vs graphql?

**Comment by jexp** [comment]
Can you share your graph schema? the output of `CALL db.schema()` ? 

Currently the IDL and graph schema have to correspond to work.

Not sure what what you mean with this

> I'm only testing the queries on static data w/o neo4j-graphql. Is there something I'm missing?

Also, What are fundamental differences with neo4j schema vs graphql?

The graphql schema inferred from the graph uses the sampled metadata.

If you post an IDL to /graphql/idl that IDL schema is used instead.

**Comment by topher** [comment]
By 'static data' I mean that I'm importing a js file with an array of objects. By 'Is there something I'm missing?' I'm referring to my conceptual understanding of graphql 

```
//affiliations.js
module.exports = [
  {
    "affn_id": "43700F3BE17145399924AC176EACBEF4",
    "name": "Richmond Senior"
  },
  {
    "affn_id": "8BDE709AC757416082950B1BEED0CE0A",
    "name": "Cedar City"
  },
  {
    "affn_id": "123D201BB17545E3B6ECCCCB5FC61FA3",
    "name": "Delta"
  }
]
```
and
```

// performances.js
module.exports = [
  {
    pfrm_id: "6BD41C6B1C4B43D199DE42A4A408DF1A",
    mark: 1270000,
    affn_id: "43700F3BE17145399924AC176EACBEF4",
  },
  {
    pfrm_id: "EA2FBC6AB891460EA557F5B60984AD8A",
    mark: 1422400,
    affn_id: "8BDE709AC757416082950B1BEED0CE0A",
  },
  {
    pfrm_id: "54A6EEB9552C49AC9F7A87E68AC272A2",
    mark: 1422400,
    affn_id: "123D201BB17545E3B6ECCCCB5FC61FA3",
  },
]
```

Here is my schema, though I'm not pulling from the db. https://pastebin.com/LcVSuVgB

I now think it is more of a graphql issue. While any tips would be appreciated, feel free to close the issue if it isn't relevant

**Comment by jexp** [comment]
@topher 
This has changed now a bit, with explicit @relation directives. Can you please try with a recent version and report back?
