### ISSUE TITLE
404 Not Found error after Install

### ISSUE THREAD

**Issue by MMJM** [neo4j-graphql/neo4j-graphql#32]
I have followed the instructions to install neo4j-graphql. The build of the code has worked and all the tests passed successfully.

I copied the specified file and edited the config file.

After restarting neo4j and creating the Movies database I was able to run this query and got some data returned. 

`CALL graphql.schema()`

What seems to be failing for me is using the URL to access graphql. I'm using http://localhost:7474/graphql/ and have added the required Authorization header.

All I seem to get is a 404 Not Found error. 

Is there anything I'm missing here? I'm pretty new to neo4j.

**Comment by jexp** [comment]
Can you share your config entry? There should also be a log entry at startup declaring that it installs the endpoint

And you copied it to the plugins directory?

**Comment by MMJM** [comment]
I am using ne04j 3.2 Community edition

Config entry is this and is in /neo4j/default.graphdb/config/neo4j.conf

`dbms.unmanaged_extension_classes=org.neo4j.graphql=/graphql`

In the plugin directory, I have 

neo4j-graphql-0.1-SNAPSHOT.jar

The `CALL graphql.schema()` function works so I'm assuming the plugin is running. I just can't seem to get to it using Postman or graphiql without getting a 404 Not Found.

**Comment by MMJM** [comment]
Would it have anything to do with CORS

**Comment by Tangmere** [comment]
I have added the following to the .neo4j.conf file instead and it looks like it is trying to start the extension but now I'm getting an error shown below. Anyone have ideas on this?

`dbms.unmanaged_extension_classes=org.neo4j.graphql=/graphql`

`Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-4970e5df@90ba62e4==org.neo4j.server.web.NeoServletContainer,-1,false`

**Comment by Tangmere** [comment]
Nightmare over.

In case anyone else is struggling with getting this running on a Mac here is what I had to do. I'm new to neo4j so I hope i'm explaining this correctly.

I had to create the plugins folder in this location and place the jar file in there. 
`/Users/???/Documents/Neo4j/default.graphdb/plugins`
This seems to get the plugin loading so you can run the function `CALL graphql.schema()`

To get this part of the setup working so you can reach the /graphql/ endpoint
`dbms.unmanaged_extension_classes=org.neo4j.graphql=/graphql`

I had to edit the config file located here `/Users/???/Documents/Neo4j/.neo4j.conf`

Starting neo4j at this point threw an error. I finally worked out you need to add the plugin inside the application contents. So on the mac 2 finger click on the Neo4j Community Edition 3.1.3.app application in `/applications/` and select `Show Package Contents`. This was new to me and i didn't know you could do that.
 
Navigate to this location and copy in the jar file.
`/Applications/Neo4j Community Edition 3.1.3.app/Contents/Resources/app/plugins`

Now start Neo4j and hopefully it should all be good and you can access `http://localhost:7474/graphql/`

**Comment by jexp** [comment]
What version of Neo4j are you using?

The extension is currently for 3.1.x

> Am 25.05.2017 um 11:25 schrieb Tangmere <notifications@github.com>:
> 
> Starting

**Comment by Tangmere** [comment]
I'm using 3.1.3

Advice to Mac users is to get the TAR ball

**Comment by rivanrashid** [comment]
@Tangmere , how did you access the following location in windows?
/Applications/Neo4j Community Edition 3.1.3.app/Contents/Resources/app/plugins

I did not find any location containing "/Applications/Neo4j Community Edition 3.1.3.app" in windows.

However in windows I have the following path containing the neo4j files where I put the jar file.
"C:\Program Files\Neo4j CE 3.1.6\plugins"

Still could not make it running in the graphiql app.

**Comment by jexp** [comment]
@rivanrashid you might need to put it into the plugins directory within your graphdb directory.

**Comment by BernhardWenzel** [comment]
Regarding the @Tangmere Mac solution, it works, but it is required to restart the mac app (it's not sufficient to just click on start button)

**Comment by FickleLife** [comment]
Thanks for this - what's the best folders to do this for a docker install?

**Comment by jexp** [comment]
You can map the Docker plugins directory and set the config option

see in the readme:

https://github.com/neo4j-graphql/neo4j-graphql#manual-installation

**Comment by FickleLife** [comment]
Thanks @jexp, I added the environment variable `-e NEO4J_dbms_unmanagedextensionclasses=org.neo4j.graphql=/graphql` but in the logs I am getting: `2019-01-02 19:36:34.604+0000 WARN  Unknown config option: dbms.unmanagedextensionclasses`, any clues?

EDIT: adding camel case 'NEO4J_dbms_unmanaged**E**xtension**C**lasses' worked for me, might be a good idea to update the docs?

**Comment by jexp** [comment]
sorry there was an rendering error in the readme

it is `-e NEO4J_dbms_unmanaged__extension__classes=org.neo4j.graphql=/graphql`
