### ISSUE TITLE
Improve returned parser errors for schema

### ISSUE THREAD

**Issue by jexp** [neo4j-graphql/neo4j-graphql#45]

**Comment by andyrichardson** [comment]
Schema errors would be a great addition. I'm currently trying to push a basic schema and only get a `500` error returned.

```
type a {
  name: String
  password: String
}
```

**Comment by jexp** [comment]
@andyrichardson and let me know if it was better?

Can you try with this build: https://dl.dropboxusercontent.com/u/14493611/neo4j-graphql-0.1-SNAPSHOT.jar
