### ISSUE TITLE
How to use the graphiql for neo4j in windows?

### ISSUE THREAD

**Issue by rivanrashid** [neo4j-graphql/neo4j-graphql#46]
Hi, I was following the read me file to run graphql with neo4j.
However, after completing all the steps when I try to use the graphiql to execute a query i get the following error:
![graphiql](https://user-images.githubusercontent.com/30704841/28943167-bfe99dc8-786b-11e7-92ec-b30b7893121c.PNG)

Another thing, what would be the Header name and header value incase the password for my neo4j server is  : rivan123
I have given in the following way:
![http_header](https://user-images.githubusercontent.com/30704841/28943321-58f35fb8-786c-11e7-8606-5cb43772af06.PNG)

The instruction given to include the basic-auth header is quite confusing.

And about using the graphql procedure from the neo4j server I am getting the following error:
![procedure](https://user-images.githubusercontent.com/30704841/28943651-8c11c6b8-786d-11e7-805d-236cd984873c.PNG)

@jexp could you please give me any clue. I just want to get the thing running. Thanks in advance!!

**Comment by johnymontana** [comment]
That looks to be an issue with the GraphiQL app you are using. Can you cURL the endpoint or use something like Postman to see if returns 209?

You can use this handy tool to generate the authorization header value: http://www.blitter.se/utils/basic-authentication-header-generator/

The header should be the standard basic auth format.

**Comment by linonetwo** [comment]
https://github.com/neo4j-graphql/neo4j-graphql/issues/13

**Comment by jexp** [comment]
Did you resolve this?

**Comment by linonetwo** [comment]
@jexp  duplicate with #13 I think.
