### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by topher** [neo4j-graphql/neo4j-graphql#47]
After installing `neo4j-graphql` with `neo4j-community-3.1.1` and using it before, I'm now having some issues executing queries.

- I'm getting a 500 server error using the electron graphql desktop app. It is able to access the movies schema though

- I'm also not able to access graphiql with the same endpoint of `http://localhost:7474/graphql` 

- GraphQL returns `SyntaxError: Unexpected end of JSON input` when entering this query:
`query AllPeopleQuery {
  Person(name:"Kevin Bacon") {
    name
  }
}`

- There were a few warning logs when launching Neo4j (in the link below) as well as:
`ERROR The RuntimeException could not be mapped to a response, re-throwing to the HTTP container Parameter specified as non-null is null: method org.neo4j.graphql.GraphQLResource.get, parameter query
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.neo4j.graphql.GraphQLResource.get, parameter query`
https://www.pastebucket.com/563386

Does anyone have insight on solving the issue?

**Comment by jexp** [comment]
Can you check if the query-variables area of GraphiQL has a `{}` entry?

**Comment by jexp** [comment]
I fixed something similar for the next release.

**Comment by jexp** [comment]
Can you try to use `http://localhost:7474/graphql/` with a trailing slash, and see if that helps?
