### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by seintelligence** [neo4j-graphql/neo4j-graphql#5]
Hi,

First, I'd like to thank you very much for this great project!

I am trying to implement it; it works very fine for query. But what about mutation?

Is there any way to push mutation through "neo4j-graphql"? How do we alter the schema to add a mutation?

Many thanks,

**Comment by jexp** [comment]
I first have to learn about these aspects of GraphQL then we have to extend the GraphQL schema and implement the mutation operations.

I was planning to continue on the deeper querying & paging things first.

What kind of operations would you need to start with?

**Comment by jexp** [comment]
Mutations are implemented now, both auto-generated as well as custom.
