### ISSUE TITLE
Support multiple query and mutation in same request

### ISSUE THREAD

**Issue by steffenkoenig** [neo4j-graphql/neo4j-graphql#59]
Currently it only seems to work to have multiple queries in the same graphql request.
Multiple mutations in same request as well as a combination of mutation and query fail.

**Comment by linonetwo** [comment]
Seems you can't do this in graphql. Just separate them by the help of packages like Apollo Client.

**Comment by linonetwo** [comment]
FYI  https://github.com/apollographql/react-apollo/issues/238

**Comment by jexp** [comment]
You can run both multiple queries as well as mutations by prefixing them with an id,like

```
mutations {
p1: createPerson("Arya")
p2: createPerson("Sansa")
}
```

**Comment by linonetwo** [comment]
@jexp  wow  I don't even know that!

**Comment by jexp** [comment]
@steffenkoenig does this solve it for you?

**Comment by steffenkoenig** [comment]
not completely,
is it also possible to have a combination of mutations and queries?

**Comment by jexp** [comment]
I think GraphQL itself doesn't support the mixing?

![fullscreen-3](https://user-images.githubusercontent.com/67427/30003788-9c071aaa-90c3-11e7-8139-4c3d98a7093e.jpg)

**Comment by jexp** [comment]
correction, you seem to be able to have multiple, when you name them
but then on "run" you have to decide for one of them
![fullscreen-4](https://user-images.githubusercontent.com/67427/30003807-e779ecc4-90c3-11e7-90ec-ec36d8c934d5.jpg)

**Comment by linonetwo** [comment]
Yes, when using apollo or relay, you use  two HOC for query and mutation.

**Comment by jexp** [comment]
I pushed a fix for the latter.

Unfortunately it only works with POST requests as operationName parameter is not passed along in GET requests by GraphiQL
