### ISSUE TITLE
Property name that matched relationship name prevented schema generation

### ISSUE THREAD

**Issue by jessitron** [neo4j-graphql/neo4j-graphql#61]
I couldn't reproduce this with trivial data, but in our real schema, we had some nodes with an "after" property and an :AFTER relationship. This gave a 500 on schema retrieval, with a "field already added" error in a builder.

Removing all the "after" properties fixed it.

**Comment by jexp** [comment]
What would be a good solution for this case? (With a hand-written schema it wouldn't happen as you'd rename it).

**Comment by jexp** [comment]
Should it perhaps not fail, but add the duplicate e.g. prefixed with an underscore and a docs comment that mentions the duplicate?

**Comment by jexp** [comment]
@jessitron wdyt?

**Comment by jexp** [comment]
ping @jessitron
