### ISSUE TITLE
Invalid schema created when node has no properties

### ISSUE THREAD

**Issue by jessitron** [neo4j-graphql/neo4j-graphql#62]
here's a simple reproduction:

`create (b: Blackberry) -[:COLOR]-> (c: Yes { name: "purple"})`

then open the client and click "Docs" to open the schema browser.
the electron graphql client says, when it tries to load the schema for its browsering:
`Error: _BlackberryOrdering values must be an object with value names as keys.`

This is also happening when I specify a schema, when it contains nodes with no properties. (This one is a serious problem for us)

**Comment by jexp** [comment]
Interestingly this only seems to be a problem on the client side, not the server side GraphQL libraries. 
I fixed it.
