### ISSUE TITLE
cypher with (this) should automatically refer to current object

### ISSUE THREAD

**Issue by steffenkoenig** [neo4j-graphql/neo4j-graphql#63]
currently when using a cypher in the schema it requires "WITH {this} AS this" to point (this) to the current object. Better would be to automatically map (this) to current object.

from slack:

Is the (this) in a cypher always supposed to be related to the object where its used in or to the first object called?

Lets say I have a schema like this:
```
type User {
  name: ID!
  roles: [Roles]
}
type Roles {
  name: ID!
  project: [Project] @relation(name:"HAS_PROJECT")
  roleset: [RoleSet] @relation(name:"HAS_SET")
  write: [RoleRight] @cypher(statement:"MATCH (this)-[:HAS_SET]->(:RoleSet)-[:CAN_WRITE]->(write:RoleRight) RETURN DISTINCT write")
  read: [RoleRight] @cypher(statement:"MATCH (this)-[:HAS_SET]->(:RoleSet)-[:CAN_READ]->(read:RoleRight) RETURN DISTINCT read")
}
type RoleSet {
  name: ID!
  write: [RoleRight] @relation(name:"CAN_WRITE")
  read: [RoleRight] @relation(name:"CAN_READ")
}
type RoleRight {
  right: ID!
}
type Project {
  name: ID!
}
```

If I now do:
```
{
 User {
  name
  roles {
   write {
     right
   }
}
}
```
I alway get all write rights even if they are not assigned to that role.
So it seems the (this) in the cypher is not referring to the current Role object

my db currently looks like this:
the user has two roles assigned and each role has different sets assigned with different rights.
But when I do the query then all rights get returned for all roles.

**Comment by jexp** [comment]
I pushed a change that fixes that, you'll have to build locally to test.

**Comment by jexp** [comment]
@steffenkoenig ping?

**Comment by steffenkoenig** [comment]
Didn't had the time yet to test.

**Comment by steffenkoenig** [comment]
Finally found time and it all seems to work..
