### ISSUE TITLE
Custom cypher in a top-level field doesn't allow nesting

### ISSUE THREAD

**Issue by jessitron** [neo4j-graphql/neo4j-graphql#68]
https://github.com/neo4j-graphql/neo4j-graphql/pull/67

**Comment by jessitron** [comment]
from adding printlns, I noticed: 

at the top level, that custom cypher runs in GraphQLSchemaBuilder.executeCypher

but if it's in a field inside a larger query, the custom cypher gets incorporated with the others in fetchGraphData, and it works then.

This does not give us a workaround right now.

**Comment by jexp** [comment]
Yes, I know, sorry. 
It's on my todo, it is a bit more tricky. But I look into this next.

**Comment by jessitron** [comment]
Since you added support for _id on selection, this is no longer urgent. Thank you for looking at it.

**Comment by jexp** [comment]
I made good progress, currently just fighting a lazy collections thingy :)

I think having this feature would be really powerful, both for custom mutations and query types.
