### ISSUE TITLE
does this really work with 3.0?

### ISSUE THREAD

**Issue by jessitron** [neo4j-graphql/neo4j-graphql#69]
I tried to use this extension with Neo 3.0.9 and got errors in cypher syntax (it didn't like | symbols) in all nested queries. Upgraded the db to 3.1.6 and it's fine.

Take the 3.0 part out of the README?

**Comment by jexp** [comment]
Sorry yes with 3.0 out of the active product lines we dropped support for that.
Also some of the new features we use, only exist in 3.1.

I remove it from the readme.
