### ISSUE TITLE
Filtering with support of a object argument for an input-argument-field

### ISSUE THREAD

**Issue by jexp** [neo4j-graphql/neo4j-graphql#7]
Filtering with support of a object argument for an input-argument-field, with key=comparator, and value compare-value

(status: {eq/neq:true}, createdAt: { gte: "2016-01-01", lt: "2016-02-01"}, tags: {isNull:false, includes/excludes: "foo"})

https://www.reindex.io/docs/graphql-api/connections/#filtering

**Comment by linonetwo** [comment]
Means we can filter with :TAG ?
