### ISSUE TITLE
Support fragments

### ISSUE THREAD

**Issue by jessitron** [neo4j-graphql/neo4j-graphql#72]
I observe that fragments are not yet supported. We'd like it if they were.

**Comment by jexp** [comment]
Do you have an example? 

We have at least some fragment support, so it would be good to see what's missing.

see here for an example what we e.g. support and test.

https://github.com/neo4j-graphql/neo4j-graphql/blob/master/src/test/java/org/neo4j/graphql/EndToEndTest.kt#L138

**Comment by jessitron** [comment]
Ah. So anonymous fragments are supported, and we want named fragments.

There's an ignored test
https://github.com/neo4j-graphql/neo4j-graphql/blob/aa6515101799bc58a0a19b80be586a295c179ed5/src/test/java/org/neo4j/graphql/MetaDataTest.java#L289
that (even when the typo is corrected) failed.

It looks to me like the library does support it, from their docs and history. But this extension does not.
