### ISSUE TITLE
Allow optional filter parameters

### ISSUE THREAD

**Issue by steffenkoenig** [neo4j-graphql/neo4j-graphql#75]
```
query Order($customer:String) {
  Order(customer:$customer) {
    amount
   date
   position { ... }
}
}
```
e.g. 
1. return specific customer if the variable is set. 
2. return all Orders if the variable is null or undefined 

Currently I would need to create two different queries. One with the (customer:$customer) and one without even though I want the same data. 

For now I overcome this issue with just using template literals in my app which is either set to 
`const customerFilter = "(customer:$customer)";` or `const customerFilter = "";` and then having my query like:
```
const gql = `query Order($customer:String) {
  Order ${customerFilter} {
    amount
   date
   position { ... }
}
}`;
```
But would be great having this option straight in the neo4j-graphql

**Comment by jexp** [comment]
This is supported now with graphcool like filters.
