### ISSUE TITLE
Potential licensing issues?

### ISSUE THREAD

**Issue by Zache** [neo4j-graphql/neo4j-graphql#81]
https://github.com/facebook/graphql/issues/351

**Comment by jexp** [comment]
Oh the joy.

**Comment by Zache** [comment]
I also realized that this might prove a problem for Neo4j as a whole. If the patents that Facebook have/wants are sufficiently broad. I'm not an expert but they read like they apply to a graph querying language, which Cypher is?

**Comment by johnsonr** [comment]
This has been solved. See https://medium.com/@leeb/relicensing-the-graphql-specification-e7d07a52301b

**Comment by jexp** [comment]
Yup, great news. Thanks Rod!
