### ISSUE TITLE
filtering with an enum type doesn't work on valid enum value

### ISSUE THREAD

**Issue by jessitron** [neo4j-graphql/neo4j-graphql#82]
This is minor, there's a super easy workaround.

This works:

```
query($buildStatus: BuildStatus) {
  Build(status: $buildStatus) {
    buildUrl
  }
}
```
with variables `{ "buildStatus": "failed" }`

but if I provide the value as a literal, I get an error:

```
query {
  Build(status: "failed") {
    buildUrl
 }
}
```

` "message": "Validation error of type WrongType: argument 'status' with value 'StringValue{value='failed'}' is not a valid 'BuildStatus'",`

Seems like a string that is a member of the enum should satisfy that. It was confusing, but the variable workaround works

**Comment by jexp** [comment]
Does the spec allow strings for enum values? The error is frommthe underlying grapql library

`{Build(status:failed) {buildUrl}}`

**Comment by jessitron** [comment]
you're right, my mistake. I need to drop the quotes.
