### ISSUE TITLE
Unable to use the built jar as plugin

### ISSUE THREAD

**Issue by Nithanaroy** [neo4j-graphql/neo4j-graphql#85]
I am trying to build the neo4j-graph extension, https://github.com/neo4j-graphql/neo4j-graphql#building-manually. I am facing these exceptions:

On first attempt to start the neo4j server after opening neo4j-community-edition-3.2.6.app:
```
Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@4e0fe757' was successfully initialized, but failed to start. Please see the attached cause exception "The ResourceConfig instance does not contain any root resource classes.".
```

On successive attempts to start server:
```
Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@55729e3a' was successfully initialized, but failed to start. Please see the attached cause exception "Multiple exceptions".
```
debug.log do not have any errors.

On googling around, looks like some problem with target/neo4j-graphql-3.2.3.1-SNAPSHOT.jar generated from `mvn clean package`. I am not sure though.

**Comment by Nithanaroy** [comment]
The problem was with the neo4j.app UI or something. Started using neo4j desktop and everything works like a charm. Would be nice if someone fixes the neo4j.app UI client app as well.

**Comment by jay-ouellette** [comment]
@Nithanaroy what command did you use to start neo4j?

**Comment by Nithanaroy** [comment]
I used neo4j community edition 3.2.6 which starts a database server behind the scenes.

**Comment by jexp** [comment]
Use Neo4j Desktop, the old UI had several weird issues (e.g. directories where to place plugins)
