### ISSUE TITLE
Issue with relationships in GraphQL schema

### ISSUE THREAD

**Issue by lyletaylor** [neo4j-graphql/neo4j-graphql#86]
I am working on get neo4j-graphql set up so I can use neo4j for a new web app I am working on, but the autogenerated schema is not matching my database schema for relationships in some cases. In particular, if the parent and child have the same label, or if the same relationship type can be used by more than one child, those relationship possibilities don't get included in the graphql schema.

For example, here is the result of calling db.schema() on my database:

![neo4jschema](https://user-images.githubusercontent.com/19439145/32301991-051be31e-bf26-11e7-8c25-fbda99aad177.png)

And here is the result of calling graphql.schema()

![neo4jgraphqlschema](https://user-images.githubusercontent.com/19439145/32302086-7acd762c-bf26-11e7-8794-217be9ad91b1.png)

Note that it created a bidirectional relationship between Area and Domain despite not being in the db schema. It did catch that Topic can belong to a Domain, but it didn't capture the fact that a Topic can belong to an Area or even another Topic.

**Comment by jexp** [comment]
Sorry for the delay
Usually in accordance with schema first we recommend to use a dedicated schema when handling any non-trivial setup (which is in your case, like duplicate relationship-types and labels).

The automatic generation will not be able to handle these trivially as you need to have differently named fields for the up and down relationships in your tree.

Please try with a dedicated schema and let me know how it goes.

**Comment by lyletaylor** [comment]
No worries. OK. Thanks. Yes, I have switched to a dedicated schema which is working much better overall and takes care of this particular issue. However, I have found an issue with the dedicated schema as well. I posted the problem I was seeing in the neo4j-graphql Slack channel.
