### ISSUE TITLE
Bug processing ID fields on supplied schema

### ISSUE THREAD

**Issue by lyletaylor** [neo4j-graphql/neo4j-graphql#87]
I am running into an issue with what neo4j-graphql thinks is an id field, and subsequently what fields it lets me supply on an update. Here is a snippet of my schema that I am supply using graphql.idl:

```
enum TagItemStatus {
    Active
    Disabled
}
type Area {
    uuid: ID!
    name: String!
    description: String
    status: TagItemStatus!
}
```

And this is the result of the call:
{Area=MetaData{type='Area', properties={uuid=PropertyInfo(fieldName=uuid, type=ID!, id=true, indexed=false, cypher=null, defaultValue=null, unique=false, enum=false, parameters=null, description=null), name=PropertyInfo(fieldName=name, type=String!, id=true, indexed=false, cypher=null, defaultValue=null, unique=false, enum=false, parameters=null, description=null), description=PropertyInfo(fieldName=description, type=String, id=false, indexed=false, cypher=null, defaultValue=null, unique=false, enum=false, parameters=null, description=null), status=PropertyInfo(fieldName=status, type=TagItemStatus!, id=false, indexed=false, cypher=null, defaultValue=null, unique=false, enum=true, parameters=null, description=null)}, labels=[], relationships={}, isInterface=false}}

If you look closely, you can see that both uuid and name have id=true. Now, when I query the schema in GraphiQL, I get this for the updateArea mutation:

```
            {
              "name": "updateArea",
              "description": "Updates a Area entity",
              "args": [
                {
                  "name": "uuid",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "SCALAR",
                      "name": "ID",
                      "ofType": null
                    }
                  },
                  "defaultValue": null
                },
                {
                  "name": "description",
                  "description": null,
                  "type": {
                    "kind": "SCALAR",
                    "name": "String",
                    "ofType": null
                  },
                  "defaultValue": null
                },
                {
                  "name": "status",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "ENUM",
                      "name": "TagItemStatus",
                      "ofType": null
                    }
                  },
                  "defaultValue": null
                }
```

Note that uuid is in the list of parameters, but not name, even though it was declared as not nullable.

**Comment by jexp** [comment]
Yes I think we have to support something like `@isUnique` or similar here.

ID field should always get priority.
